# Manuscript-ready answers, tables, and figures aligned to the original analysis plan.

source("scripts/00_setup.R")
source("R/research_output_functions.R")

participants <- read_processed("participant_analysis.csv")
item_long <- read_processed("item_long.csv")
baseline_tests <- readr::read_csv("outputs/tables/table_2_pre_item_tests_by_ae.csv", show_col_types = FALSE)
composite_tests <- readr::read_csv("outputs/tables/pre_composite_tests_by_ae.csv", show_col_types = FALSE)
prepost_tests <- readr::read_csv("outputs/tables/table_3_prepost_full_sample_tests.csv", show_col_types = FALSE)
change_by_ae_tests <- readr::read_csv("outputs/tables/table_4_prepost_change_by_ae_tests.csv", show_col_types = FALSE)
age_correlations <- readr::read_csv("outputs/tables/age_correlations.csv", show_col_types = FALSE)
age_prevalence <- readr::read_csv("outputs/tables/ae_prevalence_by_age_group_test.csv", show_col_types = FALSE)
ae_type_descriptives <- readr::read_csv("outputs/tables/ae_type_anxiety_descriptives.csv", show_col_types = FALSE)
verification_descriptives <- readr::read_csv("outputs/tables/verification_anxiety_descriptives.csv", show_col_types = FALSE)

research_answers <- rq_make_answers(baseline_tests, composite_tests, prepost_tests, change_by_ae_tests)
plan_recommendations <- rq_plan_recommendations()

sample_characteristics <- dplyr::bind_rows(
  participants |>
    dplyr::mutate(group = as.character(ae_status)) |>
    dplyr::group_by(group) |>
    dplyr::summarise(
      n = dplyr::n(),
      age_mean = mean(age, na.rm = TRUE), age_sd = stats::sd(age, na.rm = TRUE),
      age_median = stats::median(age, na.rm = TRUE), age_min = min(age, na.rm = TRUE), age_max = max(age, na.rm = TRUE),
      age_missing = sum(is.na(age)), age_uncertain = sum(age_uncertain_flag, na.rm = TRUE),
      age_tentatively_resolved = sum(age_tentatively_resolved_flag, na.rm = TRUE),
      sex = "Not available in supplied workbook", .groups = "drop"
    ),
  participants |>
    dplyr::summarise(
      group = "full sample", n = dplyr::n(),
      age_mean = mean(age, na.rm = TRUE), age_sd = stats::sd(age, na.rm = TRUE),
      age_median = stats::median(age, na.rm = TRUE), age_min = min(age, na.rm = TRUE), age_max = max(age, na.rm = TRUE),
      age_missing = sum(is.na(age)), age_uncertain = sum(age_uncertain_flag, na.rm = TRUE),
      age_tentatively_resolved = sum(age_tentatively_resolved_flag, na.rm = TRUE),
      sex = "Not available in supplied workbook"
    )
) |>
  dplyr::mutate(ae_prevalence_pct = dplyr::if_else(group == "full sample", NA_real_, 100 * n / sum(n[group != "full sample"])))

tables_for_workbook <- list(
  `Research question answers` = research_answers,
  `Table 1 sample characteristics` = sample_characteristics,
  `Table 2 baseline items` = baseline_tests,
  `Baseline composites` = composite_tests,
  `Table 3 full-sample change` = prepost_tests,
  `Table 4 change by AE` = change_by_ae_tests,
  `Age correlations` = age_correlations,
  `AE prevalence by age` = age_prevalence,
  `AE type descriptives` = ae_type_descriptives,
  `Verification descriptives` = verification_descriptives,
  `Plan recommendations` = plan_recommendations
)

write_csv_safe(research_answers, "outputs/tables/research_question_answers.csv")
write_csv_safe(sample_characteristics, "outputs/tables/research_table_1_sample_characteristics.csv")
write_csv_safe(plan_recommendations, "outputs/tables/analysis_plan_recommendations.csv")
writexl::write_xlsx(tables_for_workbook, "outputs/tables/research_questions_all_tables.xlsx")

figures <- list(
  figure_1_pre_anxiety = list(plot = rq_plot_pre_anxiety(participants), width = 7.2, height = 5.2),
  figure_2_pre_wellbeing = list(plot = rq_plot_pre_wellbeing(participants), width = 7.2, height = 5.2),
  figure_3_prepost_item6 = list(plot = rq_plot_item6_paired(item_long, participants), width = 8.2, height = 5.5),
  figure_4_ae_types_verification = list(plot = rq_plot_ae_types(participants), width = 8.2, height = 5.8),
  supplementary_figure_1_item5_6_distributions = list(plot = rq_plot_item_5_6_distributions(item_long, participants), width = 9, height = 6.2),
  supplementary_figure_2_full_sample_change = list(plot = rq_plot_full_sample_change(prepost_tests), width = 9, height = 6),
  supplementary_figure_3_ae_change_contrasts = list(plot = rq_plot_ae_change_contrasts(change_by_ae_tests), width = 9, height = 6)
)

purrr::iwalk(figures, function(spec, name) {
  ggplot2::ggsave(file.path("outputs", "figures", paste0(name, ".png")), spec$plot, width = spec$width, height = spec$height, dpi = 300, bg = "white")
  ggplot2::ggsave(file.path("outputs", "figures", paste0(name, ".pdf")), spec$plot, width = spec$width, height = spec$height, bg = "white")
})

figure_manifest <- tibble::tibble(
  figure = names(figures),
  png_300_dpi = file.path("outputs", "figures", paste0(names(figures), ".png")),
  vector_pdf = file.path("outputs", "figures", paste0(names(figures), ".pdf")),
  source = "Generated by ggplot2 from current processed data"
)
write_csv_safe(figure_manifest, "outputs/tables/research_figure_manifest.csv")

message("Research-question answers, manuscript tables, and export-ready figures written to outputs/.")
